### ISSUE TITLE
Potential double buy on partially filled orders

### ISSUE THREAD

**Issue by TheFitzZZ** [TheFitzZZ/binance-trader#1]
Is already being worked on...

**Comment by aguilardmarkanthony** [comment]
Done with the changes, in testing stage atm.

**Comment by TheFitzZZ** [comment]
Seems to sill happened:
Trade history:
``` 
2018-02-18 19:50:57 | RPX/ETH | Buy | 0.00024695 | 29 | 0.00009226 BNB | 0.00716155 ETH
2018-02-18 19:50:50 | RPX/ETH | Buy | 0.00024695 | 171 | 0.00054401 BNB | 0.04222845 ETH
```

Order history:
```
02-18 19:50:43 | RPX/ETH | Limit | Buy | 0.00024695 | 0.00024695 | 200 | 200 | 0.04939000 ETH | -- | Filled | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

But resulted only in this sell order:
```
2018/02/18 19:51:05 | RPX/ETH | Limit | Sell | 0.00024769 | 171 | 0.00% | 0.04235499 | -- |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
```

So 29 RPX were "abandoned" 👎 :-(

**Comment by TheFitzZZ** [comment]
Issue still exists - cancelled buy order when it was already partially filled, leaved already bought coins in wallet without tracking

**Comment by TheFitzZZ** [comment]
Potentially related to latency issues caused by network delays.

**Comment by aguilardmarkanthony** [comment]
Changes made. 

Get remaining unsold quantity from the last transaction, 
not that efficient but at least it will hodl the coins. 

Note: This is temporary fixed.
